@"
name: Deploy to Supabase

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest
    
    - name: Deploy functions
      run: |
        supabase functions deploy --project-ref "$SUPABASE_PROJECT_ID" --no-verify-jwt
      env:
        SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    
    - name: Deployment Success
      run: echo "🚀 Functions deployed successfully!"
"@ | Out-File -FilePath ".github\workflows\deploy.yml" -Encoding utf8